### ISSUE TITLE
Doesn't work in Zabbix 5.2.7

### ISSUE THREAD

**Issue by xenadmin** [BGmot/zabbix-module-hosts-tree#6]
The new page just stays empty. No visible errors. See attached apache error log.
```
[Thu Aug 26 14:51:20.054852 2021] [php7:error] [pid 13857] [client 1.2.3.4:3715] PHP Fatal error:  Uncaught Error: Call to undefined function getHostInterface() in /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php:142\nStack trace:\n#0 /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php(212): addGroupRow(Array, Array, 'Customer/Anaxco...', 'Customer', 1, Array)\n#1 /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php(51): addGroupRow(Array, Array, 'Customer', '', 0, Array)\n#2 /usr/share/zabbix/include/classes/mvc/CPartial.php(109): include('/usr/share/zabb...')\n#3 /usr/share/zabbix/modules/zabbix-module-hosts-tree/views/module.monitoring.bghost.view.refresh.php(23): CPartial->getOutput()\n#4 /usr/share/zabbix/include/classes/mvc/CView.php(122): include('/usr/share/zabb...')\n#5 /usr/share/zabbix/include/classes/core/ZBase.php(618): CView->getOutput()\n#6 /usr/share/zabbix/include/classes/core/ZBase.php(547): ZBase->processResponseFinal(Object(CRouter), Object(Modules\\BGmotHosts\\ in /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php on line 142, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
[Thu Aug 26 14:51:20.054886 2021] [php7:error] [pid 14325] [client 1.2.3.4:55212] PHP Fatal error:  Uncaught Error: Call to undefined function getHostInterface() in /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php:142\nStack trace:\n#0 /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php(212): addGroupRow(Array, Array, 'Customer/Anaxco...', 'Customer', 1, Array)\n#1 /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php(51): addGroupRow(Array, Array, 'Customer', '', 0, Array)\n#2 /usr/share/zabbix/include/classes/mvc/CPartial.php(109): include('/usr/share/zabb...')\n#3 /usr/share/zabbix/modules/zabbix-module-hosts-tree/views/module.monitoring.bghost.view.refresh.php(23): CPartial->getOutput()\n#4 /usr/share/zabbix/include/classes/mvc/CView.php(122): include('/usr/share/zabb...')\n#5 /usr/share/zabbix/include/classes/core/ZBase.php(618): CView->getOutput()\n#6 /usr/share/zabbix/include/classes/core/ZBase.php(547): ZBase->processResponseFinal(Object(CRouter), Object(Modules\\BGmotHosts\\ in /usr/share/zabbix/modules/zabbix-module-hosts-tree/partials/module.monitoring.host.view.html.php on line 142, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
[Thu Aug 26 14:51:20.055132 2021] [php7:error] [pid 13857] [client 1.2.3.4:3715] PHP Fatal error:  Uncaught Exception: Headers already sent. in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php:68\nStack trace:\n#0 /usr/share/zabbix/include/classes/core/CCookieSession.php(126): CCookieHelper::set('zbx_session', 'eyJzZXNzaW9uaWQ...', 1632574280)\n#1 [internal function]: CCookieSession->write('a4feeaee57ee2dc...', 'eyJzZXNzaW9uaWQ...')\n#2 {main}\n  thrown in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php on line 68, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
[Thu Aug 26 14:51:20.055243 2021] [php7:warn] [pid 13857] [client 1.2.3.4:3715] PHP Warning:  Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
[Thu Aug 26 14:51:20.055512 2021] [php7:error] [pid 14325] [client 1.2.3.4:55212] PHP Fatal error:  Uncaught Exception: Headers already sent. in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php:68\nStack trace:\n#0 /usr/share/zabbix/include/classes/core/CCookieSession.php(126): CCookieHelper::set('zbx_session', 'eyJzZXNzaW9uaWQ...', 1632574280)\n#1 [internal function]: CCookieSession->write('a4feeaee57ee2dc...', 'eyJzZXNzaW9uaWQ...')\n#2 {main}\n  thrown in /usr/share/zabbix/include/classes/helpers/CCookieHelper.php on line 68, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
[Thu Aug 26 14:51:20.055677 2021] [php7:warn] [pid 14325] [client 1.2.3.4:55212] PHP Warning:  Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0, referer: https://FQDN/zabbix/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=Zabbix%20Proxys&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=bghost.view&groupids%5B%5D=7
```

**Comment by BGmot** [comment]
Yes it does not work (currently) for 5.2. I took a quick look at the code and it seem I'd need massive changes to adapt the code to 5.2 and given that 5.2 is no longer supported I am not sure if I should invest time in this. Although I'll probably give another shot if I absolutely don't have anything to do so I am not closing this issue for now... Sorry guys.

**Comment by xenadmin** [comment]
That's okay for me, just close this issue. As long as https://github.com/BGmot/zabbix-module-latest-data works reliable, there is no need to invest any more time into 5.2.x branch.
